# Generated by Django 4.1.7 on 2023-03-03 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essai.basemodel')),
                ('ticket', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=250)),
                ('arrive', models.CharField(max_length=250)),
                ('date_voyage', models.DateTimeField()),
                ('prix_siege', models.CharField(max_length=250)),
            ],
            bases=('essai.basemodel',),
        ),
        migrations.CreateModel(
            name='profil',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essai.basemodel')),
                ('dateNaissance', models.CharField(max_length=200)),
                ('pp', models.ImageField(upload_to='image')),
                ('document', models.FileField(upload_to='docs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('essai.basemodel',),
        ),
    ]
